---
name: "🛠️ AWS S3 Publish Logs"
description: |
  This GitHub Action uploads logs to AWS S3.

inputs:
  S3_BUCKET:
    description: "AWS S3 Bucket"
    required: true
    default: "fdio-logs-s3-cloudfront-index"
    type: string
  S3_PATH:
    description: "AWS S3 Path"
    required: false
    default: "vex-yul-rot-jenkins-1/${{ github.job }}/${{ github.run_id }}/"
    type: string

runs:
  using: "composite"
  steps:
#    - name: "Upload Logs to S3 bucket"
#      run: |
#        python3 bootstrap_publish_logs.py deploy_s3 ${{ inputs.S3_BUCKET }} '${{ inputs.S3_PATH }}' '${{ github.workspace }}"
    - name: "Install AWS CLI"
      shell: bash
      env:
        CACHE_PATH: ${{ runner.temp }}/aws-cli-cache
      run: |
        ZIP_FILE_NAME="awscli-exe-linux-$(uname -m).zip"

        # Create and enter temporary directory
        mkdir -p "$CACHE_PATH"
        cd "$CACHE_PATH"

        "Downloading AWS CLI"
        curl -fsSL --retry 3 --retry-delay 5 --connect-timeout 15 --max-time 60 -o "$ZIP_FILE_NAME" "https://awscli.amazonaws.com/$ZIP_FILE_NAME"

        "Installing AWS CLI"
        unzip -o -q "$ZIP_FILE_NAME"
        sudo ./aws/install --update
        rm -rf ./aws

    - name: "Upload to S3"
      shell: bash
      run: |
        aws --version #s3 cp ${{ github.workspace }} s3://${{ inputs.S3_BUCKET }}
        echo ${{ inputs.S3_BUCKET }}
        echo ${{ inputs.S3_PATH }}