---
name: csit-dpdk-perf-report

on:
  workflow_dispatch:
    inputs:
      JOB_TYPE:
        description: "The type of job: iterative or coverage."
        required: true
        type: choice
        options:
          - iterative
          - coverage
        default: iterative
      NODE_ARCH:
        description: Number of nodes and architecture of testbed.
        required: true
        type: choice
        options:
          - 2n-emr
          - 2n-grc
          - 2n-icx
          - 2n-spr
          - 2n-zn2
          - 3n-alt
          - 3n-emr
          - 3n-icx
          - 3n-icxd
          - 3n-oct
          - 3n-snr
          - 3na-spr
          - 3nb-spr
        default: 2n-emr
      BRANCH:
        description: Branch or patch.
        required: true
        type: string
        default: rls2510
      SUITE_GEN_PARAMS:
        description: Parameters for the suite generator.
        required: true
        type: string

jobs:
  csit-dpdk-perf-report:
    # yamllint disable-line rule:line-length
    name: csit-dpdk-perf-report-${{ github.event.inputs.JOB_TYPE }}-${{ github.event.inputs.NODE_ARCH }}

    strategy:
      matrix:
        include:
          - node: 2n-emr
            os: ubuntu2404
            arch: x86_64
          - node: 2n-grc
            os: ubuntu2404
            arch: aarch64
          - node: 2n-icx
            os: ubuntu2404
            arch: x86_64
          - node: 2n-spr
            os: ubuntu2404
            arch: x86_64
          - node: 2n-zn2
            os: ubuntu2404
            arch: x86_64
          - node: 3n-alt
            os: ubuntu2404
            arch: aarch64
          - node: 3n-emr
            os: ubuntu2404
            arch: x86_64
          - node: 3n-icx
            os: ubuntu2404
            arch: x86_64
          - node: 3n-icxd
            os: ubuntu2404
            arch: x86_64
          - node: 3n-oct
            os: ubuntu2404
            arch: aarch64
          - node: 3n-snr
            os: ubuntu2404
            arch: x86_64
          - node: 3na-spr
            os: ubuntu2404
            arch: x86_64
          - node: 3nb-spr
            os: ubuntu2404
            arch: x86_64

    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=${{ matrix.arch }}
      - fdio:class=builder
      - fdio:namespace=sandbox
      - fdio:os=${{ matrix.os }}

    env:
      # yamllint disable-line rule:line-length
      JOB_NAME: csit-dpdk-perf-report-${{ github.event.inputs.JOB_TYPE }}-${{ matrix.node }}
      GERRIT_BRANCH: ${{ github.event.inputs.BRANCH }}
      GERRIT_EVENT_COMMENT_TEXT: ${{ github.event.inputs.SUITE_GEN_PARAMS }}

    steps:
      - name: Checkout CSIT repository with the change
        if: ${{ github.event.inputs.NODE_ARCH == matrix.node }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.BRANCH }}
          fetch-depth: 0

      - name: Setup Environment
        if: ${{ github.event.inputs.NODE_ARCH == matrix.node }}
        uses: pmikus/.github/.github/actions/setup_executor_env@main

      - name: Run Performance Bootstrap
        if: ${{ github.event.inputs.NODE_ARCH == matrix.node }}
        run: |
          csit_entry_dir="./resources/libraries/bash/entry"
          source ${csit_entry_dir}/bootstrap_verify_perf.sh

      - name: Archive Logs
        if: ${{ always() && github.event.inputs.NODE_ARCH == matrix.node }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.JOB_NAME }}-${{ github.run_number }}
          path: archives/
          if-no-files-found: ignore

      - name: AWS S3 Publish Logs
        if: ${{ always() && github.event.inputs.NODE_ARCH == matrix.node }}
        uses: pmikus/.github/.github/actions/aws_s3_publish_logs@main
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          S3_BUCKET: ${{ vars.S3_BUCKET }}
