---
name: csit-dpdk-perf-report

on:
  workflow_dispatch:
    inputs:
      JOB_TYPE:
        description: "The type of job: iterative or coverage."
        required: true
        type: choice
        options:
          - iterative
          - coverage
        default: iterative
      NODE_ARCH:
        description: Number of nodes and architecture of testbed.
        required: true
        type: choice
        options:
          - 2n-emr
          - 2n-grc
          - 2n-icx
          - 2n-spr
          - 2n-zn2
          - 3n-alt
          - 3n-emr
          - 3n-icx
          - 3n-icxd
          - 3n-oct
          - 3n-snr
          - 3na-spr
          - 3nb-spr
        default: 2n-emr
      BRANCH:
        description: Branch or patch.
        required: true
        type: string
        default: rls2510
      SUITE_GEN_PARAMS:
        description: Parameters for the suite generator.
        required: true
        type: string

env:
  # yamllint disable-line rule:line-length
  JOB_NAME: "csit-dpdk-perf-report-${{ github.event.inputs.JOB_TYPE }}-${{ github.event.inputs.NODE_ARCH }}"
  TESTBEDS: |
    '{
      "2n-emr": {"OS": "ubuntu2404", "EXECUTOR_ARCH": "x86_64"},
      "2n-grc": {"OS": "ubuntu2404", "EXECUTOR_ARCH": "aarch64"},
      "2n-icx": {"OS": "ubuntu2404", "EXECUTOR_ARCH": "x86_64"},
      "2n-spr": {"OS": "ubuntu2404", "EXECUTOR_ARCH": "x86_64"},
      "2n-zn2": {"OS": "ubuntu2404", "EXECUTOR_ARCH": "x86_64"},
      "3n-alt": {"OS": "ubuntu2404", "EXECUTOR_ARCH": "aarch64"},
      "3n-emr": {"OS": "ubuntu2404", "EXECUTOR_ARCH": "x86_64"},
      "3n-icx": {"OS": "ubuntu2404", "EXECUTOR_ARCH": "x86_64"},
      "3n-icxd": {"OS": "ubuntu2404", "EXECUTOR_ARCH": "x86_64"},
      "3n-oct": {"OS": "ubuntu2404", "EXECUTOR_ARCH": "aarch64"},
      "3n-snr": {"OS": "ubuntu2404", "EXECUTOR_ARCH": "x86_64"},
      "3na-spr": {"OS": "ubuntu2404", "EXECUTOR_ARCH": "x86_64"},
      "3nb-spr": {"OS": "ubuntu2404", "EXECUTOR_ARCH": "x86_64"}
    }'
  GERRIT_BRANCH: ${{ github.event.inputs.BRANCH }}
  GERRIT_EVENT_COMMENT_TEXT: ${{ github.event.inputs.SUITE_GEN_PARAMS }}

jobs:
  csit-dpdk-perf-report:
    name: ${{ github.env.JOB_NAME }}
    runs-on:
      - self-hosted
      - nomad
      # yamllint disable-line rule:line-length
      - fdio:arch=${{ fromJSON(github.env.TESTBEDS)[github.event.inputs.NODE_ARCH].EXECUTOR_ARCH }}
      - fdio:class=builder
      - fdio:namespace=sandbox
      # yamllint disable-line rule:line-length
      - fdio:os=${{ fromJSON(github.env.TESTBEDS)[github.event.inputs.NODE_ARCH].OS }}
    timeout-minutes: 3600

    steps:
      - name: Checkout CSIT repository with the change
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.BRANCH }}
          fetch-depth: 0

      - name: Setup Environment
        uses: pmikus/.github/.github/actions/setup_executor_env@main

      - name: Run Performance Bootstrap
        run: |
          csit_entry_dir="./resources/libraries/bash/entry"
          source ${csit_entry_dir}/bootstrap_verify_perf.sh

      - name: Archive Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.JOB_NAME }}-${{ github.run_number }}
          path: archives/
          if-no-files-found: "ignore"

      - name: AWS S3 Publish Logs
        if: always()
        uses: pmikus/.github/.github/actions/aws_s3_publish_logs@main
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          S3_BUCKET: ${{ vars.S3_BUCKET }}
