---
name: csit-vpp-perf-mrr-weekly

# yamllint disable-line rule:truthy
on:
  # Runs periodically
  #schedule:
  #  - cron:  "0 0 * * 1"
  workflow_dispatch:

jobs:
  csit-vpp-perf-mrr-weekly:
    name: csit-vpp-perf-mrr-weekly-master-${{ matrix.node }}
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=${{ matrix.executor_arch }}
      - fdio:class=builder
      - fdio:namespace=sandbox
      - fdio:os=${{ matrix.os }}
    timeout-minutes: 3600

    strategy:
      matrix:
        include:
          - node: 2n-aws
            os: ubuntu2404
            executor_arch: x86_64
          - node: 2n-c6in
            os: ubuntu2404
            executor_arch: x86_64
          - node: 2n-c7gn
            os: ubuntu2404
            executor_arch: aarch64

    env:
      JOB_NAME: ${{ github.job }}-master-${{ matrix.node }}

    steps:
      - name: Checkout CSIT repository with the change
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Setup Environment
        uses: pmikus/.github/.github/actions/setup_executor_env@main

      - name: Run Performance Bootstrap
        uses: pmikus/csit/.github/actions/csit-bootstrap@c7102618197f7006f62e7ff89cc7b1e08ce4940b
        with:
          BOOTSTRAP_SCRIPT: bootstrap_verify_perf.sh
          WITH_OPER: true

      - name: Archive Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.JOB_NAME }}-${{ github.run_number }}
          path: archives/
          if-no-files-found: ignore

      - name: AWS S3 Publish Logs
        if: always()
        uses: pmikus/.github/.github/actions/aws-s3-publish-logs@cfcf2a99d1936ac871865b8b9c67d488460662c1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          S3_BUCKET: ${{ vars.S3_BUCKET }}