---
name: csit-vpp-perf-mrr-daily

# yamllint disable-line rule:truthy
on:
  # Runs periodically
  #schedule:
  #  - cron:  "30 22 * * 0-4"
  workflow_dispatch:

jobs:
  csit-vpp-perf-mrr-daily:
    name: csit-vpp-perf-mrr-daily-master-${{ matrix.node }}
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=${{ matrix.executor_arch }}
      - fdio:class=builder
      - fdio:namespace=sandbox
      - fdio:os=${{ matrix.os }}
    timeout-minutes: 3600

    strategy:
      matrix:
        include:
          - node: 2n-grc
            os: ubuntu2404
            executor_arch: aarch64
          - node: 2n-icx
            os: ubuntu2404
            executor_arch: x86_64
          - node: 2n-spr
            os: ubuntu2404
            executor_arch: x86_64
          - node: 2n-zn2
            os: ubuntu2404
            executor_arch: x86_64
          - node: 3n-icx
            os: ubuntu2404
            executor_arch: x86_64
          - node: 3n-alt
            os: ubuntu2404
            executor_arch: aarch64
          - node: 3n-snr
            os: ubuntu2404
            executor_arch: x86_64
          - node: 3n-icxd
            os: ubuntu2404
            executor_arch: x86_64
          - node: 3na-spr
            os: ubuntu2404
            executor_arch: x86_64
          - node: 3nb-spr
            os: ubuntu2404
            executor_arch: x86_64
          - node: 2n-emr
            os: ubuntu2404
            executor_arch: x86_64
          - node: 3n-emr
            os: ubuntu2404
            executor_arch: x86_64
          - node: 3n-oct
            os: ubuntu2404
            executor_arch: aarch64

    env:
      JOB_NAME: "${{ github.job }}-master-${{ matrix.node }}"

    steps:
      - name: Checkout CSIT repository with the change
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Setup Environment
        uses: pmikus/.github/.github/actions/setup_executor_env@main

      - name: Run Performance Bootstrap
        env:
          BRANCH_ID: oper
          GERRIT_BRANCH: master
        run: |
          csit_entry_dir="./resources/libraries/bash/entry"
          source ${csit_entry_dir}/with_oper_for_vpp.sh "bootstrap_verify_perf.sh"

      - name: Archive Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.JOB_NAME }}-${{ github.run_number }}
          path: archives/
          if-no-files-found: "ignore"

      - name: AWS S3 Publish Logs
        if: always()
        uses: pmikus/.github/.github/actions/aws_s3_publish_logs@main
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          S3_BUCKET: ${{ vars.S3_BUCKET }}