---
name: csit-terraform-aws-eb-version

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

concurrency:
  # yamllint disable-line rule:line-length
  group: verify-${{ github.workflow }}-${{ github.event.inputs.GERRIT_BRANCH }}-${{ github.event.inputs.GERRIT_CHANGE_ID || github.run_id }}
  cancel-in-progress: true

jobs:
  verify:
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=x86_64
      - fdio:class=builder
      - fdio:namespace=sandbox
      - fdio:os=ubuntu2404

    env:
      JOB_NAME: csit-terraform-aws-eb-version-verify
      BUILD_ID: ${{ github.run_number }}

    steps:
      - name: Checkout CSIT repository with the change
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Setup Environment
        uses: pmikus/.github/.github/actions/setup_executor_env@main

      - name: Run Terraform Bootstrap
        run: |
          csit_entry_dir="./resources/libraries/bash/entry"
          source ${csit_entry_dir}/bootstrap_aws_eb_version_verify.sh

  deploy:
    needs: verify
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=x86_64
      - fdio:class=builder
      - fdio:namespace=sandbox
      - fdio:os=ubuntu2404

    env:
      JOB_NAME: csit-terraform-aws-eb-version-deploy
      BUILD_ID: ${{ github.run_number }}

    steps:
      - name: Checkout CSIT repository with the change
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Setup Environment
        uses: pmikus/.github/.github/actions/setup_executor_env@main

      - name: Run Terraform Bootstrap
        run: |
          csit_entry_dir="./resources/libraries/bash/entry"
          source ${csit_entry_dir}/bootstrap_aws_eb_version_deploy.sh
