---
name: CSIT Performance

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      GERRIT_BRANCH:
        description: "Branch that change is against"
        required: true
        type: string
      GERRIT_CHANGE_ID:
        description: "The ID for the change"
        required: true
        type: string
      GERRIT_CHANGE_NUMBER:
        description: "The Gerrit number"
        required: true
        type: string
      GERRIT_CHANGE_URL:
        description: "URL to the change"
        required: true
        type: string
      GERRIT_EVENT_TYPE:
        description: "Type of Gerrit event"
        required: true
        type: string
      GERRIT_PATCHSET_NUMBER:
        description: "The patch number for the change"
        required: true
        type: string
      GERRIT_PATCHSET_REVISION:
        description: "The revision sha"
        required: true
        type: string
      GERRIT_PROJECT:
        description: "Project in Gerrit"
        required: true
        type: string
      GERRIT_REFSPEC:
        description: "Gerrit refspec of change"
        required: true
        type: string
      TARGET_REPO:
        # yamllint disable-line rule:line-length
        description: "The target GitHub repository needing the required workflow"
        required: true
        type: string

concurrency:
  # yamllint disable-line rule:line-length
  group: required-verify-${{ github.workflow }}-${{ github.event.inputs.GERRIT_BRANCH }}-${{ github.event.inputs.GERRIT_CHANGE_ID || github.run_id }}
  cancel-in-progress: true

jobs:
  csit-vpp-perf-verify:
    name: csit-vpp-perf-verify-${{ matrix.os }}
    runs-on:
      - self-hosted
      - nomad
      - fdio:arch=${{ matrix.executor_arch }}
      - fdio:class=builder
      - fdio:namespace=${{ matrix.builder_type }}
      - fdio:os=${{ matrix.os }}

    strategy:
      matrix:
        builder_type: [sandbox]
        include:
          - node: "2n-aws"
            os: ubuntu2404
            executor_arch: x86_64
          - node: "2n-c6in"
            os: ubuntu2404
            executor_arch: x86_64
          - node: "2n-c7gn"
            os: ubuntu2404
            executor_arch: aarch64
          - node: "2n-icx"
            os: ubuntu2404
            executor_arch: x86_64

    env:
      JOB_NAME: "${{ github.job }}-${{ inputs.GERRIT_BRANCH }}-${{ matrix.node }}"

    steps:
      - name: Gerrit Checkout
        # yamllint disable-line rule:line-length
        uses: lfit/checkout-gerrit-change-action@54d751e8bd167bc91f7d665dabe33fae87aaaa63 # v0.9
        with:
          gerrit-refspec: ${{ inputs.GERRIT_REFSPEC }}
          gerrit-project: ${{ inputs.GERRIT_PROJECT }}
          gerrit-url: ${{ vars.GERRIT_URL }}
          delay: "0s"
          repository: ${{ inputs.TARGET_REPO }}
          ref: refs/heads/${{ inputs.GERRIT_BRANCH }}

      - name: "Retrieve GIT commit message"
        uses: lfit/releng-reusable-workflows/.github/actions/git-commit-message-action@main

      - name: Setup Environment
        uses: pmikus/csit/.github/actions/setup_executor_env@master

      - name: Run Verify Performance
        run: |
          source ./resources/libraries/bash/entry/bootstrap_verify_perf.sh"

      - name: Archive Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.JOB_NAME }}-${{ github.run_number }}
          path: archives/log.html
          if-no-files-found: "ignore"